import React, { useState } from 'react';
import {
  ScrollView,
  View,
  Text,
  TextInput,
  Pressable,
  StyleSheet,
  ActivityIndicator,
  Share,
  Platform,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import Markdown from 'react-native-markdown-display';
import { palette, radius, spacing, typography } from '../theme';
import { Card, PrimaryButton, GhostButton, H1, H2, H3, Body, Small, SectionLabel } from '../components/UI';
import { assessEligibility, EligibilityVerdict } from '../lib/api';
import { markdownStyles } from '../components/markdownStyles';

const DIAGNOSES = [
  { id: 'Dementia / Alzheimer\'s', scale: 'FAST' },
  { id: 'CHF / Heart Failure', scale: 'NYHA' },
  { id: 'COPD / End-stage Lung', scale: 'PPS' },
  { id: 'Cancer', scale: 'PPS' },
  { id: 'ESRD / Renal Failure', scale: 'PPS' },
  { id: 'ESLD / Liver Failure', scale: 'PPS' },
  { id: 'Stroke / CVA', scale: 'PPS' },
  { id: 'Adult Failure to Thrive', scale: 'PPS' },
  { id: 'Parkinson\'s / Neurodegenerative', scale: 'PPS' },
  { id: 'ALS', scale: 'PPS' },
  { id: 'Other / Debility', scale: 'PPS' },
];

const INDICATOR_OPTIONS = [
  'Weight loss > 10% in 6 months',
  'Albumin < 2.5 or low protein status',
  'Recurrent infections (UTI, pneumonia, sepsis)',
  '2+ hospitalizations in 6 months',
  '2+ ER visits in 6 months',
  'Pressure ulcer Stage 3 or 4',
  'Recurrent aspiration',
  'Decreased oral intake / dysphagia',
  'Significant decline in ADLs',
  'Bed-bound or chair-bound > 50% of day',
  'Family has stopped pursuing curative treatment',
  'Goals of care shifting toward comfort',
];

const FAST_OPTIONS = ['7A', '7B', '7C', '7D', '7E', '7F'];
const PPS_OPTIONS = ['10%', '20%', '30%', '40%', '50%', '60%', '70%'];
const NYHA_OPTIONS = ['Class III', 'Class IV'];

export default function EligibilityScreen() {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [diagnosis, setDiagnosis] = useState<string>('');
  const [age, setAge] = useState<string>('');
  const [indicators, setIndicators] = useState<string[]>([]);
  const [functionalScore, setFunctionalScore] = useState<string>('');
  const [recentEvents, setRecentEvents] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<{ verdict: EligibilityVerdict; summary: string } | null>(null);

  const diagObj = DIAGNOSES.find((d) => d.id === diagnosis);
  const scale = diagObj?.scale || 'PPS';
  const scaleOptions = scale === 'FAST' ? FAST_OPTIONS : scale === 'NYHA' ? NYHA_OPTIONS : PPS_OPTIONS;
  const totalSteps = 4;

  const toggleIndicator = (i: string) =>
    setIndicators((cur) => (cur.includes(i) ? cur.filter((x) => x !== i) : [...cur, i]));

  const canProceed = () => {
    if (step === 0) return !!diagnosis;
    if (step === 1) return indicators.length >= 1;
    if (step === 2) return !!functionalScore;
    return true;
  };

  const submit = async () => {
    setLoading(true);
    try {
      const r = await assessEligibility({
        diagnosis,
        age: age ? parseInt(age, 10) : undefined,
        indicators,
        functionalScale: scale,
        functionalScore,
        recentEvents: recentEvents || undefined,
      });
      setResult(r);
    } catch (e: any) {
      setResult({
        verdict: 'POSSIBLE',
        summary: '⚠️ Could not generate a clinical summary right now. Please try again in a moment.',
      });
    } finally {
      setLoading(false);
    }
  };

  const shareSummary = async () => {
    if (!result) return;
    const text = `Spartan Coaching — Hospice Eligibility Quick Check\n\nDiagnosis: ${diagnosis}\nVerdict: ${verdictLabel(result.verdict)}\n\n${result.summary}\n\n— Generated by the Spartan Coaching iOS app.`;
    try {
      if (Platform.OS === 'web' && (navigator as any).share) {
        await (navigator as any).share({ title: 'Hospice Eligibility Quick Check', text });
      } else if (Platform.OS === 'web') {
        await navigator.clipboard.writeText(text);
      } else {
        await Share.share({ message: text });
      }
    } catch (e) {
      // no-op
    }
  };

  if (result) {
    return (
      <SafeAreaView edges={['bottom']} style={{ flex: 1, backgroundColor: palette.bg }}>
        <ScrollView contentContainerStyle={{ padding: spacing.l, paddingBottom: 100 }}>
          <SectionLabel>Quick Check Result</SectionLabel>
          <H1 style={{ marginBottom: spacing.s }}>Hospice Readiness</H1>
          <Small dim style={{ marginBottom: spacing.l }}>{diagnosis} · {scale} {functionalScore}</Small>

          <LinearGradient
            colors={verdictColors(result.verdict)}
            style={styles.verdictCard}
          >
            <View style={styles.verdictIcon}>
              <Ionicons name={verdictIcon(result.verdict)} size={32} color="#fff" />
            </View>
            <Text style={styles.verdictLabel}>{verdictLabel(result.verdict)}</Text>
            <Text style={styles.verdictSub}>{verdictSubtext(result.verdict)}</Text>
          </LinearGradient>

          <Card style={{ marginBottom: spacing.l }}>
            <Markdown style={markdownStyles}>{result.summary}</Markdown>
          </Card>

          <View style={{ gap: 10 }}>
            <PrimaryButton
              testID="elig-share"
              label="Share with hospice intake"
              onPress={shareSummary}
              icon={<Ionicons name="share-outline" size={16} color="#fff" />}
            />
            <GhostButton
              testID="elig-talk-to-nick"
              label="Talk to Nick about this case"
              onPress={() => router.push('/(tabs)/more')}
              icon={<Ionicons name="chatbubbles-outline" size={16} color={palette.text} />}
            />
            <GhostButton
              testID="elig-restart"
              label="Run another check"
              onPress={() => {
                setResult(null);
                setStep(0);
                setDiagnosis('');
                setAge('');
                setIndicators([]);
                setFunctionalScore('');
                setRecentEvents('');
              }}
            />
          </View>

          <Card style={{ marginTop: spacing.l, backgroundColor: palette.bgElev2, borderColor: palette.warn + '40' }}>
            <View style={{ flexDirection: 'row', gap: 10, alignItems: 'flex-start' }}>
              <Ionicons name="information-circle" size={20} color={palette.warn} />
              <Small dim style={{ flex: 1 }}>
                Educational tool only. Not a clinical determination. Final hospice eligibility requires physician certification per Medicare guidelines.
              </Small>
            </View>
          </Card>
        </ScrollView>
      </SafeAreaView>
    );
  }

  if (loading) {
    return (
      <SafeAreaView edges={['bottom']} style={{ flex: 1, backgroundColor: palette.bg }}>
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.xl, gap: spacing.l }}>
          <ActivityIndicator color={palette.primary} size="large" />
          <H3 style={{ textAlign: 'center' }}>Generating clinical summary…</H3>
          <Small dim style={{ textAlign: 'center', maxWidth: 280 }}>
            Cross-referencing your inputs against Medicare LCD criteria.
          </Small>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView edges={['bottom']} style={{ flex: 1, backgroundColor: palette.bg }}>
      <ScrollView contentContainerStyle={{ padding: spacing.l, paddingBottom: 100 }}>
        <View style={{ flexDirection: 'row', gap: 4, marginBottom: spacing.l }}>
          {Array.from({ length: totalSteps }).map((_, i) => (
            <View
              key={i}
              style={[
                styles.progressDot,
                i <= step && { backgroundColor: palette.primary },
              ]}
            />
          ))}
        </View>

        <SectionLabel>Quick Check · 60 seconds</SectionLabel>
        <H2 style={{ marginBottom: spacing.s }}>Hospice Eligibility</H2>
        <Body dim style={{ marginBottom: spacing.l }}>
          A guided clinical snapshot that produces a shareable hospice-readiness summary aligned to Medicare LCDs. No PHI required.
        </Body>

        {step === 0 && (
          <>
            <H3 style={{ marginBottom: spacing.s, fontSize: 17 }}>1. Primary diagnosis</H3>
            <Body dim style={{ marginBottom: spacing.m }}>What is the main terminal condition?</Body>
            <View style={{ gap: 6 }}>
              {DIAGNOSES.map((d) => (
                <Pressable
                  key={d.id}
                  testID={`elig-dx-${d.id}`}
                  onPress={() => setDiagnosis(d.id)}
                  style={({ pressed }) => [
                    styles.option,
                    diagnosis === d.id && styles.optionActive,
                    { opacity: pressed ? 0.85 : 1 },
                  ]}
                >
                  <Text style={[styles.optionText, diagnosis === d.id && { color: palette.primary }]}>{d.id}</Text>
                  {diagnosis === d.id && <Ionicons name="checkmark-circle" size={20} color={palette.primary} />}
                </Pressable>
              ))}
            </View>

            <Small style={[styles.lbl, { marginTop: spacing.l }]}>Approximate age (optional)</Small>
            <TextInput
              testID="elig-age"
              value={age}
              onChangeText={setAge}
              placeholder="e.g., 78"
              placeholderTextColor={palette.textFaint}
              style={styles.input}
              keyboardType="numeric"
              maxLength={3}
            />
          </>
        )}

        {step === 1 && (
          <>
            <H3 style={{ marginBottom: spacing.s, fontSize: 17 }}>2. Decline indicators</H3>
            <Body dim style={{ marginBottom: spacing.m }}>Select all that apply. At least one is required.</Body>
            <View style={{ gap: 6 }}>
              {INDICATOR_OPTIONS.map((i) => {
                const selected = indicators.includes(i);
                return (
                  <Pressable
                    key={i}
                    testID={`elig-ind-${i.slice(0, 24)}`}
                    onPress={() => toggleIndicator(i)}
                    style={({ pressed }) => [
                      styles.option,
                      selected && styles.optionActive,
                      { opacity: pressed ? 0.85 : 1 },
                    ]}
                  >
                    <View style={[styles.checkbox, selected && styles.checkboxActive]}>
                      {selected && <Ionicons name="checkmark" size={14} color="#fff" />}
                    </View>
                    <Text style={[styles.optionText, { flex: 1 }, selected && { color: palette.primary }]}>{i}</Text>
                  </Pressable>
                );
              })}
            </View>
          </>
        )}

        {step === 2 && (
          <>
            <H3 style={{ marginBottom: spacing.s, fontSize: 17 }}>3. Functional status ({scale})</H3>
            <Body dim style={{ marginBottom: spacing.m }}>
              {scale === 'FAST'
                ? 'FAST scale staging for dementia. 7A or greater typically supports hospice eligibility.'
                : scale === 'NYHA'
                ? 'NYHA functional class for heart failure. Class III/IV combined with other indicators is required.'
                : 'Palliative Performance Scale (PPS). 50% or below combined with other indicators is required.'}
            </Body>
            <View style={styles.scaleRow}>
              {scaleOptions.map((s) => (
                <Pressable
                  key={s}
                  testID={`elig-scale-${s}`}
                  onPress={() => setFunctionalScore(s)}
                  style={({ pressed }) => [
                    styles.scaleChip,
                    functionalScore === s && styles.scaleChipActive,
                    { opacity: pressed ? 0.85 : 1 },
                  ]}
                >
                  <Text style={[styles.scaleChipText, functionalScore === s && { color: '#fff' }]}>{s}</Text>
                </Pressable>
              ))}
            </View>
          </>
        )}

        {step === 3 && (
          <>
            <H3 style={{ marginBottom: spacing.s, fontSize: 17 }}>4. Recent events (optional)</H3>
            <Body dim style={{ marginBottom: spacing.m }}>
              Anything else relevant — hospitalizations, ER visits, recent procedures, conversations about goals of care. No patient identifiers.
            </Body>
            <TextInput
              testID="elig-events"
              value={recentEvents}
              onChangeText={setRecentEvents}
              placeholder="e.g., Two hospitalizations in the past 4 months for sepsis. Family expressed preference for comfort care last week."
              placeholderTextColor={palette.textFaint}
              style={[styles.input, { minHeight: 120, textAlignVertical: 'top' }]}
              multiline
            />

            {/* Summary preview */}
            <Card style={{ marginTop: spacing.l }}>
              <Small style={{ color: palette.primary, fontWeight: '700', marginBottom: spacing.s }}>
                READY TO ASSESS
              </Small>
              <SummaryRow label="Diagnosis" value={diagnosis} />
              {age && <SummaryRow label="Age" value={age} />}
              <SummaryRow label="Scale" value={`${scale} ${functionalScore}`} />
              <SummaryRow label="Indicators" value={`${indicators.length} selected`} />
            </Card>
          </>
        )}

        <View style={{ flexDirection: 'row', gap: 10, marginTop: spacing.xl }}>
          {step > 0 && (
            <View style={{ flex: 1 }}>
              <GhostButton testID="elig-back" label="Back" onPress={() => setStep((s) => Math.max(0, s - 1))} />
            </View>
          )}
          <View style={{ flex: 2 }}>
            {step < totalSteps - 1 ? (
              <PrimaryButton
                testID="elig-next"
                label="Next"
                onPress={() => setStep((s) => s + 1)}
                disabled={!canProceed()}
                icon={<Ionicons name="arrow-forward" size={14} color="#fff" />}
              />
            ) : (
              <PrimaryButton
                testID="elig-assess"
                label="Generate summary"
                onPress={submit}
                disabled={!canProceed() || loading}
                icon={<Ionicons name="sparkles" size={14} color="#fff" />}
              />
            )}
          </View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

function SummaryRow({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.summaryRow}>
      <Text style={styles.summaryLabel}>{label}</Text>
      <Text style={styles.summaryValue} numberOfLines={2}>{value}</Text>
    </View>
  );
}

function verdictLabel(v: EligibilityVerdict) {
  if (v === 'LIKELY') return 'Likely Eligible';
  if (v === 'POSSIBLE') return 'Possibly Eligible';
  return 'Not Yet Eligible';
}
function verdictSubtext(v: EligibilityVerdict) {
  if (v === 'LIKELY') return 'Clinical picture aligns with Medicare LCD criteria. Recommend formal evaluation.';
  if (v === 'POSSIBLE') return 'Some indicators present. Clinical confirmation needed.';
  return 'Insufficient decline indicators at this time. Reassess in 30-60 days.';
}
function verdictColors(v: EligibilityVerdict): [string, string] {
  if (v === 'LIKELY') return ['#16a34a', '#065f46'];
  if (v === 'POSSIBLE') return ['#f59e0b', '#b45309'];
  return ['#6b7280', '#374151'];
}
function verdictIcon(v: EligibilityVerdict): keyof typeof Ionicons.glyphMap {
  if (v === 'LIKELY') return 'checkmark-circle';
  if (v === 'POSSIBLE') return 'help-circle';
  return 'time';
}

const styles = StyleSheet.create({
  progressDot: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: palette.bgElev3,
  },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: palette.bgElev1,
    borderWidth: 1,
    borderColor: palette.cardBorder,
    borderRadius: radius.md,
  },
  optionActive: {
    borderColor: palette.primary,
    backgroundColor: palette.primaryTint,
  },
  optionText: { color: palette.text, fontSize: 14, flexShrink: 1, fontWeight: '600' },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: palette.cardBorderStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxActive: { backgroundColor: palette.primary, borderColor: palette.primary },
  lbl: { color: palette.text, fontWeight: '700', marginBottom: 6 },
  input: {
    backgroundColor: palette.bgElev2,
    borderColor: palette.cardBorder,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: palette.text,
    fontSize: 15,
  },
  scaleRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  scaleChip: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: radius.md,
    backgroundColor: palette.bgElev1,
    borderWidth: 1,
    borderColor: palette.cardBorder,
    minWidth: 70,
    alignItems: 'center',
  },
  scaleChipActive: { backgroundColor: palette.primary, borderColor: palette.primary },
  scaleChipText: { color: palette.text, fontSize: 15, fontWeight: '700' },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderColor: palette.divider,
    gap: 16,
  },
  summaryLabel: { color: palette.textDim, fontSize: 13, fontWeight: '600' },
  summaryValue: { color: palette.text, fontSize: 13, fontWeight: '700', flexShrink: 1, textAlign: 'right', maxWidth: 220 },
  verdictCard: {
    padding: spacing.xl,
    borderRadius: radius.xl,
    marginBottom: spacing.l,
    alignItems: 'center',
  },
  verdictIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  verdictLabel: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '900',
    letterSpacing: -0.5,
    marginBottom: 6,
  },
  verdictSub: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
  },
});
